// Mock data for courses, topics, and words

export const mockCourses = [
  {
    id: '1',
    name: 'IELTS Foundation',
    description: 'Khóa học IELTS cơ bản cho người mới bắt đầu',
    level: 'Beginner',
    topicCount: 15,
    wordCount: 450,
    studentCount: 234,
    price: 299000,
    thumbnail: '📚',
    progress: 0,
    isEnrolled: false,
    isFree: false,
  },
  {
    id: '2',
    name: 'Business English',
    description: 'Tiếng Anh giao tiếp trong môi trường công sở',
    level: 'Intermediate',
    topicCount: 20,
    wordCount: 600,
    studentCount: 156,
    price: 399000,
    thumbnail: '💼',
    progress: 0,
    isEnrolled: false,
    isFree: false,
  },
  {
    id: '3',
    name: 'Daily Conversation',
    description: 'Giao tiếp hàng ngày trong cuộc sống',
    level: 'Beginner',
    topicCount: 12,
    wordCount: 360,
    studentCount: 432,
    price: 0,
    thumbnail: '🗣️',
    progress: 35,
    isEnrolled: true,
    isFree: true,
  },
  {
    id: '4',
    name: 'TOEIC Preparation',
    description: 'Luyện thi TOEIC đạt điểm cao',
    level: 'Intermediate',
    topicCount: 18,
    wordCount: 540,
    studentCount: 189,
    price: 499000,
    thumbnail: '📝',
    progress: 0,
    isEnrolled: false,
    isFree: false,
  },
  {
    id: '5',
    name: 'Travel & Tourism',
    description: 'Từ vựng và giao tiếp khi đi du lịch',
    level: 'Beginner',
    topicCount: 10,
    wordCount: 300,
    studentCount: 312,
    price: 0,
    thumbnail: '✈️',
    progress: 60,
    isEnrolled: true,
    isFree: true,
  },
  {
    id: '6',
    name: 'Academic Writing',
    description: 'Viết học thuật cho IELTS và TOEFL',
    level: 'Advanced',
    topicCount: 16,
    wordCount: 480,
    studentCount: 98,
    price: 599000,
    thumbnail: '✍️',
    progress: 0,
    isEnrolled: false,
    isFree: false,
  },
];

export const mockTopicsByCourse: Record<string, any[]> = {
  '3': [
    {
      id: '1',
      courseId: '3',
      name: 'Greetings & Introductions',
      wordCount: 45,
      duration: '30 min',
      progress: 100,
      isCompleted: true,
      isLocked: false,
      thumbnail: '👋',
    },
    {
      id: '2',
      courseId: '3',
      name: 'Food & Dining',
      wordCount: 67,
      duration: '45 min',
      progress: 60,
      isCompleted: false,
      isLocked: false,
      thumbnail: '🍽️',
    },
    {
      id: '3',
      courseId: '3',
      name: 'Shopping & Money',
      wordCount: 52,
      duration: '35 min',
      progress: 0,
      isCompleted: false,
      isLocked: false,
      thumbnail: '🛍️',
    },
    {
      id: '4',
      courseId: '3',
      name: 'Travel & Transportation',
      wordCount: 58,
      duration: '40 min',
      progress: 0,
      isCompleted: false,
      isLocked: false,
      thumbnail: '🚗',
    },
    {
      id: '5',
      courseId: '3',
      name: 'Weather & Seasons',
      wordCount: 41,
      duration: '30 min',
      progress: 0,
      isCompleted: false,
      isLocked: true,
      thumbnail: '🌤️',
    },
    {
      id: '6',
      courseId: '3',
      name: 'Health & Medical',
      wordCount: 63,
      duration: '45 min',
      progress: 0,
      isCompleted: false,
      isLocked: true,
      thumbnail: '🏥',
    },
  ],
  '5': [
    {
      id: '7',
      courseId: '5',
      name: 'At the Airport',
      wordCount: 35,
      duration: '25 min',
      progress: 100,
      isCompleted: true,
      isLocked: false,
      thumbnail: '✈️',
    },
    {
      id: '8',
      courseId: '5',
      name: 'Hotel Check-in',
      wordCount: 42,
      duration: '30 min',
      progress: 80,
      isCompleted: false,
      isLocked: false,
      thumbnail: '🏨',
    },
    {
      id: '9',
      courseId: '5',
      name: 'Asking for Directions',
      wordCount: 38,
      duration: '28 min',
      progress: 0,
      isCompleted: false,
      isLocked: false,
      thumbnail: '🗺️',
    },
  ],
};

export const mockWordsByTopic: Record<string, any[]> = {
  '1': [
    {
      id: '1',
      topicId: '1',
      word: 'Hello',
      phonetic: '/həˈloʊ/',
      translation: 'Xin chào',
      partOfSpeech: 'interjection',
      example: 'Hello! How are you today?',
      exampleTranslation: 'Xin chào! Hôm nay bạn thế nào?',
      isMastered: true,
    },
    {
      id: '2',
      topicId: '1',
      word: 'Goodbye',
      phonetic: '/ˌɡʊdˈbaɪ/',
      translation: 'Tạm biệt',
      partOfSpeech: 'interjection',
      example: 'Goodbye! See you tomorrow.',
      exampleTranslation: 'Tạm biệt! Hẹn gặp lại ngày mai.',
      isMastered: true,
    },
    {
      id: '3',
      topicId: '1',
      word: 'Please',
      phonetic: '/pliːz/',
      translation: 'Làm ơn, xin vui lòng',
      partOfSpeech: 'adverb',
      example: 'Please help me with this.',
      exampleTranslation: 'Làm ơn giúp tôi việc này.',
      isMastered: false,
    },
    {
      id: '4',
      topicId: '1',
      word: 'Thank you',
      phonetic: '/θæŋk juː/',
      translation: 'Cảm ơn',
      partOfSpeech: 'phrase',
      example: 'Thank you for your help.',
      exampleTranslation: 'Cảm ơn sự giúp đỡ của bạn.',
      isMastered: false,
    },
    {
      id: '5',
      topicId: '1',
      word: 'Sorry',
      phonetic: '/ˈsɑːri/',
      translation: 'Xin lỗi',
      partOfSpeech: 'adjective',
      example: 'I am sorry for being late.',
      exampleTranslation: 'Tôi xin lỗi vì đến muộn.',
      isMastered: false,
    },
    {
      id: '6',
      topicId: '1',
      word: 'Excuse me',
      phonetic: '/ɪkˈskjuːz miː/',
      translation: 'Xin lỗi (để xin phép)',
      partOfSpeech: 'phrase',
      example: 'Excuse me, where is the bathroom?',
      exampleTranslation: 'Xin lỗi, phòng tắm ở đâu?',
      isMastered: false,
    },
    {
      id: '7',
      topicId: '1',
      word: 'Nice to meet you',
      phonetic: '/naɪs tuː miːt juː/',
      translation: 'Rất vui được gặp bạn',
      partOfSpeech: 'phrase',
      example: 'Nice to meet you! My name is John.',
      exampleTranslation: 'Rất vui được gặp bạn! Tên tôi là John.',
      isMastered: false,
    },
  ],
  '2': [
    {
      id: '8',
      topicId: '2',
      word: 'Restaurant',
      phonetic: '/ˈrestərɑːnt/',
      translation: 'Nhà hàng',
      partOfSpeech: 'noun',
      example: 'We went to a nice restaurant last night.',
      exampleTranslation: 'Chúng tôi đã đến một nhà hàng đẹp tối qua.',
      isMastered: true,
    },
    {
      id: '9',
      topicId: '2',
      word: 'Menu',
      phonetic: '/ˈmenjuː/',
      translation: 'Thực đơn',
      partOfSpeech: 'noun',
      example: 'Can I see the menu, please?',
      exampleTranslation: 'Cho tôi xem thực đơn được không?',
      isMastered: false,
    },
    {
      id: '10',
      topicId: '2',
      word: 'Delicious',
      phonetic: '/dɪˈlɪʃəs/',
      translation: 'Ngon',
      partOfSpeech: 'adjective',
      example: 'This food is delicious!',
      exampleTranslation: 'Món ăn này ngon quá!',
      isMastered: false,
    },
  ],
};

// Helper functions
export function getCourseById(id: string) {
  return mockCourses.find(c => c.id === id);
}

export function getTopicsByCourseId(courseId: string) {
  return mockTopicsByCourse[courseId] || [];
}

export function getTopicById(topicId: string) {
  for (const topics of Object.values(mockTopicsByCourse)) {
    const topic = topics.find(t => t.id === topicId);
    if (topic) return topic;
  }
  return null;
}

export function getWordsByTopicId(topicId: string) {
  return mockWordsByTopic[topicId] || [];
}
